### PR TITLE
Crowdin stuff

### LINKED ISSUE #36: Add Crowdin Github Action
The Crowdin Github action would allow us to automatically sync translations from our Crowdin, removing a lot of headache from the process of localisation.

### PR DESCRIPTION
**Pull request by KTrain5169**
# Pull request template

## Category

- [ ] Add mod to alternatives page
- [ ] Site changes
- [x] Chore/documentation updates

## Describe changes
Added GitHub Action that automatically pulls from Crowdin and updates strings. Also adds a translation progress badge to README because why not?

## Why did you do this?
Makes it easier to integrate with Crowdin. The current solution being used at StopMalwareContent (owned by Nitrrine) is apparently not the best? And using the CLI via `pnpm` may expose secrets.

## BREAKING CHANGES

- [ ] Tick this box if you made changes that may or may not break site functionality.

## What issues (if any) would this resolve?

Resolves #36 

## Extra notes?
This PR **should not** be merged until all secrets are set. The secrets that need to be set are the following:
* CROWDIN_PROJECT_ID (this can be obtained by having @blryface go to [this webpage](https://crowdin.com/project/notessential/tools/api) and finding it there)
* CROWDIN_PERSONAL_TOKEN (can be created at [Crowdin's API key page](https://crowdin.com/settings#api-key). Once again requires @blryface to do it probably)
* A token that "has the repo scope selected" (Crowdin GitHub Action Page said this). I think a `contents: write` GITHUB_TOKEN should work, but if for some reason it doesn't (I can't test rn due to some factors namely requiring Crowdin strings to be not updated I think?) then a collaborator/owner of the repo needs to create a GitHub PAT with the scope selected.

## Checklist

- [ ] I have put clear & concise details about the mod onto the page.
- [ ] Links I have put in are all valid.
- [ ] Mods added are not RATs.

- [ ] I have clearly stated why I want this to be changed.
- [ ] For major changes, I have clearly stated what they are and why I've done them.
- [ ] Any new resources put in are safe and not malicious.

- [x] I have clearly explained why I have done this.
- [x] I have proofread the documentation changed and have ensured there are no spelling or grammatical errors.
- [ ] (Workflow updates only) I have tested the workflow to ensure its functionality.

- [x] I have searched for duplicate PRs and have not found any.
- [ ] I did not read this section.

Vercel will begin deploying to the Preview environment shortly after submitting this pull request. You may click on the "Visit Preview" link below to see a preview of what your changes look like.
If you updated only part of the repository such that it would not modify the website at all, you do not need to see the Vercel deployment.

You may also use the StackBlitz Codeflow button to quickview the PR in the browser and make changes at the same time if necessary.

### CODE REVIEW

**Comment by KTrain5169** [comment]
*sigh* why is PR workflow refusing to work properly

**Comment by worldwidepixel** [comment]
image
Uhh...

**Comment by KTrain5169** [comment]
You gotta be kidding me...
I'll look into it later today then

**Comment by worldwidepixel** [comment]
Loving the ***@***.***

**Comment by blryface** [comment]
what should i do :unknown~1:

**Comment by worldwidepixel** [comment]
cool

**Review by blryface — APPROVED** [review]
lgtm

**Review by worldwidepixel — APPROVED** [review]
10/10 would review again

**Comment by worldwidepixel** [comment]
@KTrain5169 Blurry has set up all environment variables on the Vercel for NotEssential.

**Comment by KTrain5169** [comment]
> @KTrain5169 Blurry has set up all environment variables on the Vercel for NotEssential.

nice...

**Comment by KTrain5169** [comment]
yes, you did it wrong

they already reviewed it

**Comment by KTrain5169** [comment]
uh... I kinda can't?

**Comment by worldwidepixel** [comment]
image

**Comment by worldwidepixel** [comment]
Now we just need to check with @KTrain5169 that all is in order and we can merge

**Review by worldwidepixel — APPROVED** [review]

**Comment by KTrain5169** [comment]
I need to double-check some things regarding the workflow and the necessary files (I can't remember if the crowdin.yml is supposed to be placed in the branch root or in .github and I can't check right now)

So yeah don't merge it yet I'll merge it myself in a couple of hours

**Pull request merged**
